/*
 * ClojureCalc.idl
 *
 * Created on 2015.05.05 - 23:53:58
 *
 */

#ifndef _com_github_beothorn_clojurecalc_ClojureCalc_
#define _com_github_beothorn_clojurecalc_ClojureCalc_

#include "XClojureCalc.idl"

module com { module github { module beothorn { module clojurecalc {
    service ClojureCalc : XClojureCalc;
}; }; }; };

#endif
